// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['wailsadapter']['Backend']['Cancel']();
}

export function InspectResume(arg1) {
  return window['go']['wailsadapter']['Backend']['InspectResume'](arg1);
}

export function OpenOutputFolder() {
  return window['go']['wailsadapter']['Backend']['OpenOutputFolder']();
}

export function Preflight(arg1) {
  return window['go']['wailsadapter']['Backend']['Preflight'](arg1);
}

export function SelectFolder() {
  return window['go']['wailsadapter']['Backend']['SelectFolder']();
}

export function SelectOutput(arg1) {
  return window['go']['wailsadapter']['Backend']['SelectOutput'](arg1);
}

export function Start(arg1) {
  return window['go']['wailsadapter']['Backend']['Start'](arg1);
}
