// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function Cancel():Promise<void>;

export function InspectResume(arg1:string):Promise<app.ResumeInspection>;

export function OpenOutputFolder():Promise<void>;

export function Preflight(arg1:app.RunRequest):Promise<app.PreflightResult>;

export function SelectFolder():Promise<string>;

export function SelectOutput(arg1:string):Promise<string>;

export function Start(arg1:app.RunRequest):Promise<void>;
